# -*- makefile -*-

srcdir = $(HOME)/soft/pe/lr-essence
PGGDIR = $(HOME)/soft/pe/cps-mcogen
CPS_MCOGEN = $(HOME)/soft/pe/cps-mcogen/cps-mcogen
COGEN_FLAGS = --verbose
CC = gcc
CFLAGS = -O
DIRECT_GENEXT = $(srcdir)/direct/direct-lr-genext.scm

PARSER_GOAL = parse
PARSER_CPS_GOAL = $(PARSER_GOAL)
PARSER_DIRECT_GOAL = $(PARSER_GOAL)

GAMBIT_DECLARATIONS = (declare (block) (standard-bindings) (not safe) (fixnum))
GSC = gsc
GAMBIT_FLAGS = -verbose
GAMBIT_INCLUDES =  -I/afs/informatik.uni-tuebingen.de/rs_aix32/pu/gambit-c-2.3.1/include
GAMBIT_CC = $(CC)
GAMBIT_CFLAGS = $(CFLAGS) -D___SINGLE_HOST $(GAMBIT_INCLUDES)
GAMBIT_LDFLAGS = -L/afs/informatik.uni-tuebingen.de/rs_aix32/pu/gambit-c-2.3.1/lib -lgambc -lm

gentime_support = $(srcdir)/common/memo.scm $(srcdir)/common/error.scm \
	$(srcdir)/common/the-trick.scm $(srcdir)/common/lookahead.scm
spectime_support = $(srcdir)/common/source-grammar.scm $(srcdir)/common/lr-spectime.scm
runtime_support = $(srcdir)/common/source-grammar.scm $(srcdir)/common/lr-runtime.scm


# Compilation with Gambit-C

%-gambit.scm: %.scm
	(echo "$(GAMBIT_DECLARATIONS)"; \
	 echo "(include \"$<\")" ; \
	) > $@; \

.PRECIOUS: %-gambit.c %-gambit.o
%-gambit.c: %-gambit.scm
	$(GSC) $(GAMBIT_FLAGS) $(@:.c=.scm)

%-gambit.o: %-gambit.c
	$(GAMBIT_CC) $(GAMBIT_CFLAGS) -c $< -o $@

%-gambit_.o: %-gambit_.c
	$(GAMBIT_CC) $(GAMBIT_CFLAGS) -c $< -o $@
