; Copyright (c) 2000-2008 by Michael Sperber and Peter Thiemann. See file COPYING.

(define i08-1 (list (cons (enum g08-symbol l) #f)
		    (cons (enum g08-symbol r) #f)
		    (cons (enum g08-symbol l) #f)
		    (cons (enum g08-symbol l) #f)
		    (cons (enum g08-symbol r) #f)
		    (cons (enum g08-symbol r) #f)))

(define i08-2 (list (cons (enum g08-symbol l) #f)
		    (cons (enum g08-symbol l) #f)
		    (cons (enum g08-symbol l) #f)
		    (cons (enum g08-symbol l) #f)
		    (cons (enum g08-symbol r) #f)
		    (cons (enum g08-symbol r) #f)))

(define i08-3 (list (cons (enum g08-symbol l) #f)
		    (cons (enum g08-symbol r) #f)
		    (cons (enum g08-symbol l) #f)
		    (cons (enum g08-symbol l) #f)
		    (cons (enum g08-symbol r) #f)
		    (cons (enum g08-symbol r) #f)
		    (cons (enum g08-symbol l) #f)))

(define i10-1 (list (cons (enum g10-symbol l) #f)
		    (cons (enum g10-symbol n) 4)
		    (cons (enum g10-symbol +) #f)
		    (cons (enum g10-symbol n) 17)
		    (cons (enum g10-symbol r) #f)
		    (cons (enum g10-symbol *) #f)
		    (cons (enum g10-symbol n) 7)))

(define i10-2 (list (cons (enum g10-symbol l) #f)
		    (cons (enum g10-symbol n) 4)
		    (cons (enum g10-symbol +) #f)
		    (cons (enum g10-symbol n) 15)
		    (cons (enum g10-symbol n) 17)
		    (cons (enum g10-symbol r) #f)
		    (cons (enum g10-symbol *) #f)
		    (cons (enum g10-symbol n) 7)))

(define i10-3 (list (cons (enum g10-symbol l) #f)
		    (cons (enum g10-symbol n) 4)
		    (cons (enum g10-symbol +) #f)
		    (cons (enum g10-symbol n) 17)
		    (cons (enum g10-symbol *) #f)
		    (cons (enum g10-symbol n) 7)))

(define i10e-1 (list (cons (enum g10-error-symbol l) #f)
		     (cons (enum g10-error-symbol n) 4)
		     (cons (enum g10-error-symbol +) #f)
		     (cons (enum g10-error-symbol n) 17)
		     (cons (enum g10-error-symbol r) #f)
		     (cons (enum g10-error-symbol *) #f)
		     (cons (enum g10-error-symbol n) 7)))

(define i10e-2 (list (cons (enum g10-error-symbol l) #f)
		     (cons (enum g10-error-symbol n) 4)
		     (cons (enum g10-error-symbol +) #f)
		     (cons (enum g10-error-symbol n) 15)
		     (cons (enum g10-error-symbol n) 17)
		     (cons (enum g10-error-symbol r) #f)
		     (cons (enum g10-error-symbol *) #f)
		     (cons (enum g10-error-symbol n) 7)))

(define i10e-3 (list (cons (enum g10-error-symbol l) #f)
		     (cons (enum g10-error-symbol n) 4)
		     (cons (enum g10-error-symbol +) #f)
		     (cons (enum g10-error-symbol n) 17)
		     (cons (enum g10-error-symbol *) #f)
		     (cons (enum g10-error-symbol n) 7)))

(define i14-1 (list (cons (enum g14-symbol lbracket) #f)
		    (cons (enum g14-symbol const) #f)
		    (cons (enum g14-symbol rbracket) #f)))
