(define-primitive = - pure)
(define-primitive < - pure)
(define-primitive > - pure)
(define-primitive equal? - pure)
(define-primitive eqv? - pure)
;; (define-primitive stream-car - pure)
(define-primitive stream-cdr - pure)
(define-primitive stream-empty? - pure)
;; (define-primitive car - pure)
(define-primitive cdr - pure)
(define-primitive not - pure)
(define-primitive - - pure)
(define-primitive zero? - pure)
