(define-primitive = - pure)
(define-primitive < - pure)
(define-primitive > - pure)
(define-primitive equal? - pure)
(define-primitive eqv? - pure)
(define-primitive null? - pure)
; (define-primitive car - pure)
(define-primitive cdr - pure)
(define-primitive not - pure)
(define-primitive - - pure)
(define-primitive zero? - pure)
(define-primitive memv - pure)
(define-primitive cons - pure)
